services:
  frontend-tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    container_name: dockmon-frontend-tests
    environment:
      - CI=true
    volumes:
      - ./ui:/app/ui
      - /app/ui/node_modules  # Prevent overwriting node_modules
    command: npm test -- --run
