services:
  dockmon:
    image: dockmon:latest  # Use pre-built image instead of building
    container_name: dockmon
    restart: unless-stopped
    ports:
      - "8001:443"   # HTTPS
    environment:
      - TZ=UTC
      - PYTHONPATH=/app/backend
      - PYTHONUNBUFFERED=1
    volumes:
      # Use bind mount to explicit host directory for data persistence
      - ./dockmon-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.dockmon.description=All-in-One Docker Container Monitor"
      - "com.dockmon.version=1.0"